config/routes.rb
Rails.application.routes.draw do
  resources :experiences
  resources :sections
  root to: 'pages#index'

  resources :tests
  resources :questions

  resources :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :test
  has_many :questions
  # has_rich_text :description
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def section_params
      params.require(:section).permit(:title, :description)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-block btn-primary" %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <h1>Editing Section</h1>

      <%= render 'form', section: @section %>

      <%= link_to 'Show', @section, class: "btn btn-block btn-primary" %>
      <%= link_to 'Back', sections_path, class: "btn btn-block btn-primary" %>
    </div>
  </div>
</div>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.description %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3 mt-3 mb-3">

      <% unless notice.nil? %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <div class="card my-3">
        <div class="card-body">

          <p>
            <strong>Test Title:</strong>
            <%= @section.test.title %>
          </p>
          <p>
            <strong>Section Title:</strong>
            <%= @section.title %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= @section.description %>
          </p>

          <% if @section.questions.size > 0 %>
            <p><strong>Questions (<%= @section.questions.size %>):</strong></p>
            <% @section.questions.each_with_index do |question, index| %>
              <p><%= index + 1 %>. <%= question.description %></p>

              <%= link_to "#", class: "btn btn-block btn-primary" do %>
                  A. <%= question.option_1 %>
              <% end %>
              <%= link_to "#", class: "btn btn-block btn-primary" do %>
                  B. <%= question.option_2 %>
              <% end %>
              <%= link_to "#", class: "btn btn-block btn-primary" do %>
                  C. <%= question.option_3 %>
              <% end %>
              <%= link_to "#", class: "btn btn-block btn-primary" do %>
                  D. <%= question.option_4 %>
              <% end %>
              <%= link_to "#", class: "btn btn-block btn-primary" do %>
                E. <%= question.option_5 %>
              <% end %>
            <% end %>
          <% end %>

        </div>
      </div>

      <%= link_to 'Edit', edit_section_path(@section), class: "btn btn-block btn-primary" %>
      <%= link_to 'Back', sections_path, class: "btn btn-block btn-primary" %>

    </div>
  </div>
</div>