config/routes.rb
Rails.application.routes.draw do
  resources :experiences
  resources :sections
  root to: 'pages#index'

  resources :tests
  resources :questions

  resources :users
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]
  before_action :set_test, except: [:new, :show]

  def index
    @experiences = Experience.all
  end

  def show
    @test = Test.find(@experience.test_id)
  end

  def new
    @test = Test.find(params[:test])
    if current_user.nil?
      @user = User.new
      @user.password = "saved_for_a_stranger"
      @user.email = "blank#{Time.now.to_f.floor.to_s}@blank.com"
      @user.save
    else
      @user = current_user
    end

    @experience = Experience.new
  end

  def edit
  end

  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_experience
      @experience = Experience.find(params[:id])
    end

    def set_test
      @test = Test.find(params[:experience][:test_id])
    end

    def experience_params
      params.require(:experience).permit(:user_id, :pass, :grade, :test_id)
    end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
        <% experience.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :pass, value: false %>
  <%= form.hidden_field :grade, value: "none"  %>
  <%= form.hidden_field :test_id, value: @test.id  %>
  <%= form.hidden_field :user_id, value: @user.id  %>

  <div class="actions">
    <%= form.submit "Start the Test", class: "btn btn-block btn-primary" %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing Experience</h1>

<%= render 'form', experience: @experience %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Experiences</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Pass</th>
      <th>Grade</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.user_id %></td>
        <td><%= experience.pass %></td>
        <td><%= experience.grade %></td>
        <td><%= experience.test_id %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card my-3">
        <div class="card-body">
          <h2>
            <%= @test.title %> (<%= @test.acronym %>)
          </h2>
          <p><%= @test.description %></p>
          <p>
            The <%= @test.acronym %>
            is made up of <%= pluralize(@test.sections.size, "section") %>
            with varying time constraints.
          </p>

          <%= render 'form', experience: @experience %>
          <%= link_to 'Back', tests_path, class: "btn btn-block btn-secondary my-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-12">
      <h1 class="text-center my-5"><%= @test.title %></h1>
    </div>

    <div class="col-md-4">
      <div class="list-group" id="list-tab" role="tablist">
        <% @test.sections.each_with_index do |section, index| %>
          <a class="list-group-item list-group-item-action <%= ' active' if index == 0 %>" id="list-profile-<%= section.title.downcase.gsub(" ", "-") %>" data-toggle="list" href="#list-<%= section.title.downcase.gsub(" ", "-") %>" role="tab" aria-controls="profile">
            <%= section.title %>
            <span class="float-right">
              Questions:
              <%= section.questions.size %>
            </span>
          </a>
        <% end %>
      </div>
      <%= link_to 'Quit and Fail Test', experiences_path, class: "btn btn-block btn-danger my-3" %>
    </div>

    <div class="col-md-8">
      <div class="tab-content" id="nav-tabContent">
        <% @test.sections.each_with_index do |section, index| %>
          <div class="tab-pane fade<%= ' show active' if index == 0 %>"
               id="list-<%= section.title.downcase.gsub(" ", "-") %>"
               role="tabpanel"
               aria-labelledby="list-<%= section.title.downcase.gsub(" ", "-") %>-list">

            <div class="card mb-3">
              <div class="card-body">
                <div class="row">
                  <div class="col-8">
                    <h2><%= section.title %></h2>
                    <p><%= section.description %></p>
                    <p><%= section.duration_descrption if section.duration_descrption %></p>
                  </div>
                  <div class="col-4">
                    <a class="btn btn-success btn-block btn-primary" data-toggle="collapse"
                       href="#collapse<%= section.title.downcase.gsub(" ", "-") %>"
                       role="button" aria-expanded="false"
                       aria-controls="collapse<%= section.title.downcase.gsub(" ", "-") %>">
                      Begin Test
                    </a>

                    <span id='timer <%= section.title.downcase.gsub(" ", "-") %>'>timer_space</span>
                  </div>
                </div>
              </div>
            </div>

            <div class="collapse" id="collapse<%= section.title.downcase.gsub(" ", "-") %>">
              <div class="card">
                <ul class="list-group list-group-flush">
                  <% section.questions.each_with_index do |question, index| %>
                    <li class="list-group-item">
                      <div class="my-3">
                        <div class="col-12">
                          <%= index + 1 %>. <%= question.description %>
                        </div>
                      </div>
                      <div class="my-3" id="<%= section.title.downcase.gsub(" ", "-") + "-" + index.to_s %>">
                        <%= link_to question.option_1, "#", class: "btn btn-block btn-primary", on_Click:"hideAndStore()" %>
                        <%= link_to question.option_2, "#", class: "btn btn-block btn-primary", on_Click:"hideAndStore()" %>
                        <%= link_to question.option_3, "#", class: "btn btn-block btn-primary", on_Click:"hideAndStore()" %>
                        <%= link_to question.option_4, "#", class: "btn btn-block btn-primary", on_Click:"hideAndStore()" %>
                        <%= link_to question.option_5, "#", class: "btn btn-block btn-primary", on_Click:"hideAndStore()" %>
                      </div>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>

          </div>
        <% end %>
      </div>
    </div>

  </div>
</div>